env:
  token: "ENCRYPTED[!414ff46c26e638f951714c8741af7b51f77812c4eb08d3076a0ed56607437bea241448e1b1657187d71cdd63f9214bee!]"

  chat_id: "ENCRYPTED[!655813cb6986b79acdf80606f20b48274840a8ff388e13c01fd1964ccfb0f6ec22304c635c1d473b00ce3f39939e6874!]"

  GH_TOKEN: "ENCRYPTED[!289e4d330898be91b3aeb2600ffc7d57346c85a5da0fa41132b5541c41c46fae0a50c1e132c744bd52695323c6dae5ee!]"

task:
  name: "Kernel deploy.."
  timeout_in: 120m
  container:
    image: accupara/aosp:ubuntu
    cpu: 8
    memory: 32G
    stateful: true
    greedy: true
  Build_script:

    - #git clone https://github.com/sksayz5/Build_Script.git -b main RMX1901 && cd RMX1901
    - #bash build.sh

     #curl -s https://raw.githubusercontent.com/sksayz5/build-script/refs/heads/main/build.sh | bash
      bash <(curl -sL https://github.com/sksayz5/build-script/raw/refs/heads/main/build.sh)
